@startuml

:Player:

Player -> (Choose Players)
Player --> (Check Rank List)
(Choose Players) .> (Choose Name) : include
(Choose Name) ..> (Answer Quiz) : include
(Answer Quiz) ..> (Check Rank List) : include
@enduml